title: 笔记
description: ""
author:
  name: 能饮一杯吴
  email: 1175791112@qq.com

# 官方主题 minima v3
theme: minima
  skin: auto
date_format: "%b-%d-%Y"

minima:
  skin: classic
  nav_pages:
    - index.md
    - categories.md
    - about.md

# 你的 /Notes 笔记目录
collections:
  Notes:
    output: true
    permalink: /Notes/:title/

# 构建配置（官方原版）
markdown: kramdown
kramdown:
  input: GFM

mathjax: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 网址
url: "https://gene5is.github.io"
baseurl: ""
